### ISSUE TITLE
Problem in !sh run_training.sh

### ISSUE THREAD

**Issue by mitra8814** [Jacobsolawetz/large-scale-oie#5]
Hi Dear,
I want to thank you for your project and your code.
I'm running your project on google colab.
when I run: 
!sh run_training.sh
I get this error:

I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.7/dist-packages/allennlp/commands/__init__.py", line 118, in main
    import_module_and_submodules(package_name)
  File "/usr/local/lib/python3.7/dist-packages/allennlp/common/util.py", line 345, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/large-scale-oie/large_scale_oie/__init__.py", line 1, in <module>
    from large_scale_oie.dataset_readers import *
  File "/content/large-scale-oie/large_scale_oie/dataset_readers/__init__.py", line 1, in <module>
    from large_scale_oie.dataset_readers.oie_reader import OieReader
  File "/content/large-scale-oie/large_scale_oie/dataset_readers/oie_reader.py", line 12, in <module>
    from allennlp.data.dataset_readers.dataset_utils import Ontonotes, OntonotesSentence
ImportError: cannot import name 'Ontonotes' from 'allennlp.data.dataset_readers.dataset_utils' (/usr/local/lib/python3.7/dist-packages/allennlp/data/dataset_readers/dataset_utils/__init__.py)

Please help me! What do I do?

**Comment by mitra8814** [comment]
I can solve it:
We should install:
!pip install allennlp-models
!pip freeze | grep allennlp

It's OK.
but when I run:
!sh run_training.sh
I get this error:
ModuleNotFoundError: No module named 'large_scale_oie'

now, what do I do?

**Comment by mitra8814** [comment]
I installed alennlp=2.4.0 and allennlp-models, but I get this error.
